name: C++ CI (Ninja)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build-type: [Release]

    runs-on: ${{ matrix.os }}

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Ninja on Windows
      - name: Install Ninja on Windows
        if: runner.os == 'Windows'
        run: choco install ninja -y

      # Set up CMake
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: "3.25.0"

      # Configure CMake with Ninja
      - name: Configure project
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      # Build project
      - name: Build project
        run: cmake --build build --config ${{ matrix.build-type }} -- -j 2

      # Run tests
      - name: Run tests
        run: ctest --test-dir build --output-on-failure --build-config ${{ matrix.build-type }}
