name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout source
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make

      # Configure CMake
      - name: Configure project
        run: |
          cmake -S . -B build

      # Build
      - name: Build project
        run: |
          cmake --build build -j

      # Run tests (GoogleTest via ctest)
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
